name: Build Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
           sudo apt update
           sudo apt install android-sdk-libsparse-utils bmap-tools debootstrap qemu-user-static rsync systemd-container

      - name: Build!
        run: |
          sudo ./build.sh -t nothingphone1
